apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: microtask-app
  labels:
    identifer: service-label
  annotations:
    identifyname: service-annotation
spec:
  type: ClusterIP
  selector:
    app: microtask-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
