apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: microtask-frontend-route
  namespace: teklu-soft-dev
spec:
  path: /
  to:
    kind: Service
    name: microtask-frontend-service
  port:
    targetPort: 3000
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
