apiVersion: v1
kind: Service
metadata:
  name: microtask-frontend-service
  namespace: teklu-soft-dev
  labels:
    identifer: service-label
  annotations:
    identifyname: service-annotation
spec:
  type: ClusterIP
  selector:
    app: microtask-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
